/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    " (OFF)": " (关)",
    " (ON)": " (开)",
    ". Latest changes are as follows:": "。 最新变更如下：",
    "Achievement Unlocked": "解锁成就",
    "Achievements Unlocked:": "解锁成就：",
    "Active Master": "活跃大师",
    "Added leader greetings & minor bug fixes": "添加了领导问候和小错误修复",
    "Advancements": "进阶",
    "Advancements Bought:": "购买的进阶：",
    "Age:": "时代：",
    "Apprentice": "学徒",
    "Available": "可用",
    "Banker": "银行家",
    "Base Click Power:": "基本点击功率：",
    "Beginner": "初学者",
    "Builder": "建设者",
    "Building Cost Multiplier:": "建筑成本乘数：",
    "Buildings": "建筑物",
    "Buildings:": "建筑物：",
    "Change Default Menu": "更改默认菜单",
    "Change Graphics": "更改图形",
    "Change Greeting": "更改问候语",
    "Change Messages Text Size": "更改消息文字大小",
    "Change Resource Rate Decimals": "更改资源率小数",
    "Change Theme": "改变主题",
    "Clicks:": "点击次数：",
    "Colonies Started:": "殖民地开始：",
    "Commerce": "商业",
    "Craven": "懦夫",
    "Current Achievement Points:": "当前成就点：",
    "Current Gold:": "当前黄金：",
    "Current Graphics:": "当前图形：",
    "Current Greeting:": "当前问候语：",
    "Current Prestige Points:": "当前声望点：",
    "Current Size:": "目前的规模：",
    "Current Theme:": "当前主题：",
    "Current Tooltips:": "当前工具提示：",
    "Currently Rounding:": "目前四舍五入：",
    "Decimal Places:": "小数点位数：",
    "Default (Dark)": "默认（深色）",
    "Delete Save Button:": "删除保存按钮：",
    "Detailed": "详细信息",
    "Enabled": "已开启",
    "Export Save": "导出保存",
    "Going Somewhere": "去某个地方",
    "Hidden": "隐藏",
    "Hungry": "饥饿",
    "Import Save": "导入保存",
    "Informed": "消息灵通",
    "Journeyman": "熟手",
    "Keep Last Tab": "保留最后一个选项卡",
    "Latest\n                                Changes": "最新\n更改",
    "Latest Changes": "最新变化",
    "Light": "光",
    "Messages": "消息",
    "Metal Caster": "金属脚轮",
    "Monk": "僧侣",
    "Normal": "普通",
    "On Load:": "负载：",
    "Passive Thinker": "被动思考者",
    "Pause": "暂停",
    "Polymath": "博学者",
    "Prestige": "声望",
    "Prestige Skills Bought:": "购买的声望技能：",
    "Progress Completion Multiplier:": "进度完成乘数：",
    "Realm Name:": "领域名称：",
    "Skip\n                                Beginning": "跳过\n开头",
    "Smithy": "铁匠铺",
    "Start a Colony": "建立殖民地",
    "The Sleeper": "沉睡者",
    "Theban Reign": "底比斯统治",
    "Theologian": "神学家",
    "Thirsty": "口渴",
    "This upgrade is free!": "本次升级是免费的！",
    "Toggle Autoskip Beginning": "切换自动跳过开头",
    "Toggle Hard Reset Option": "切换硬重置选项",
    "Toggle Resource Bar Rounding": "切换资源栏四舍五入",
    "Toggle Tooltip Modes": "切换工具提示模式",
    "Toggle Tutorial Tips": "Toggle 教程提示",
    "Trader": "商人",
    "Trades Done:": "已完成交易：",
    "Tutorial:": "教程：",
    "Upgrade Cost Multiplier:": "升级成本乘数：",
    "Upgrades": "升级",
    "Upgrades Bought:": "购买的升级：",
    "Upon Reset:": "重置后：",
    "Variety Expert": "专家类型",
    "Water": "水",
    "Welcome to": "欢迎来到",
    "Welcome to Clicker Ultimate!": "欢迎来到 Clicker Ultimate！",
    "Will of the People": "人民的意志",
    "Worker Cost Multiplier:": "工人成本乘数：",
    "Workers": "工人",
    "Workers:": "工人：",
    "Close": "关闭",
    "Copy to Clipboard": "复制到剪贴板",
    "Livonian Federation": "利沃尼亚联邦",
    "Copy/Paste the following text to import your game:": "复制/粘贴以下文本以导入您的游戏存档：",
    "You see a river from which you can carry water with your hands. It seems like it will take some work.": "你看到一条河，你可以用手从河里提水。 看来这需要一些工作。",
    "or": "或",
    ". Do you see where this is heading?": "。 你知道这将走向何方吗？",
    ". May you heed their advice.": "。 愿你听从他们的建议。",
    ". Time to get serious.": "。 是时候认真起来了。",
    ". Wait a minute, are you even paying these people?": "。 等一下，你还付钱给这些人吗？",
    ". What are these shiny metals for anyway?": "。 这些闪亮的金属到底有什么用呢？",
    "A simple worker that carries water back to your stockage. A single worker gives you": "一个简单的工人将水运回你的仓库。 一个工人给你",
    "Acquire your first": "获得你的第一个",
    "advancement.": "进阶。",
    "and": "和",
    "and purchase a total of": "并总共购买",
    "and receive the first passive bonus granted by their pious fervor.": "并获得他们虔诚的热情所授予的第一个被动奖励。",
    "Are you getting somewhere yet? Reach": "你有进展吗？ 抵达",
    "at a rate of": "以速率",
    "Back to the Smithy with you": "和你一起回到铁匠铺",
    "Banking": "银行业",
    "Build": "建造",
    "Build an impressive total of": "建立令人印象深刻的总数",
    "Build your first": "构建你的第一个",
    "button above to fill the Progress Bar of a resource. Doing so will grant you resources which you can use to buy things with.": "上面的按钮来填充资源的进度条。 这样做将为您提供可用来购买东西的资源。",
    "Carrying water by yourself has become tiresome. Making others do it for you will help.": "自己一个人挑水已经很累了。 让别人为你做这件事会有帮助。",
    "Currently gives you:": "目前为您提供：",
    "Discover": "发现",
    "Discover the benefits of": "发现以下好处",
    "Discover the method of cutting trees down to keep natural resources for yourself. This might lead to a better future.": "探索砍伐树木的方法，为自己保留自然资源。 这可能会带来更美好的未来。",
    "Economics": "经济学",
    "Farmer": "农民",
    "Fire": "火",
    "Foundry": "铸造厂",
    "Gather": "收集",
    "Hire a total of": "总共雇用",
    "Hire your first": "雇用你的第一个",
    "in a single colony. Embody the art of micromanagement.": "在一个单一的殖民地。 体现微观管理的艺术。",
    "Let There Be Light": "要有光",
    "Lumberjack": "伐木工",
    "Miner": "矿工",
    "My power of thought calls you, sleeper. Acquire your first": "我的思想力量在召唤你，沉睡者。 获得你的第一个",
    "No amount of prestige points can cure your carpal tunnel syndrome. Reach": "再多的声望点也无法治愈你的腕管综合症。 抵达",
    "Passive Bonus": "被动奖金",
    "Perform a total of": "总共执行",
    "Recruit your first": "招募你的第一个",
    "Research the": "研究",
    "The only way to craft your empire, click by click. Reach": "打造你的帝国的唯一方法是点击点击。 抵达",
    "The real clicker is the friends we make along the way. Reach": "真正的点击者是我们一路上结识的朋友。 抵达",
    "Theology": "神学",
    "This achievement is hidden.": "这个成就是隐藏的。",
    "TIP: Click on the": "提示：单击",
    "TIP: You can hover over the tile of a": "提示：您可以将鼠标悬停在某个图块上",
    "to see what it does and how much it costs. The more workers you have, the more their effects stack!": "看看它的作用和成本是多少。 你拥有的工人越多，他们的效果叠加就越多！",
    "Trades": "交易",
    "under your employ. Why would you do this?": "在你的雇佣下。 你为什么要这样做？",
    "Water Fetcher": "取水工",
    "Water Fetching": "取水",
    "without ever having a single": "从未拥有过",
    "without having to resort to using any of the": "无需诉诸于使用任何",
    "Woodcutting": "伐木",
    "Worker": "工人",
    "You hired a water fetcher and/or a lumberjack.": "您雇用了一名取水工和/或一名伐木工人。",
    "Arctic Metal": "北极金属",
    "Crimson Sky": "赤红天空",
    "Disabled": "禁用",
    "Indigo Rush": "靛蓝拉什",
    "Lightning Strike": "雷击",
    "Quiet Night": "安静的夜晚",
    "Simple": "简单",
    "Turtle": "龟",
    "Version Number": "版本号",
    "Victory": "胜利",
    "Did you know? If you click on the name of a resource, you can get more information about what affects it and how you are collecting it.": "你可知道？ 如果单击资源名称，您可以获得有关影响该资源的因素以及如何收集该资源的更多信息。",
    "Wood": "木头",
    "A simple worker that carries wood back to your stockage. A single worker gives you": "一个简单的工人将木材运回您的仓储。 一个工人给你",
    "Click on the": "点击",
    "Dominion of Assyria": "亚述统治",
    "You can hover over the tile of a": "您可以将鼠标悬停在某个图块上",
    ", look for numbers right of the upgrade's name indicating which tier you are looking at.": "，查找升级名称右侧的数字，表明您正在查看哪个级别。",
    ", meaning they can be bought more than once. When hovering over the tile of an": "，这意味着它们可以多次购买。 当鼠标悬停在某个图块上时",
    "bar, instead of": "酒吧，而不是",
    "have several": "有几个",
    "Some": "一些",
    "Tiers": "等级",
    "Upgrade": "升级",
    "Water, you will gain": "水，你将收获",
    "Your lumberjack suggests making a bucket for you to carry more water. Everytime you complete the": "您的伐木工人建议您制作一个水桶来装更多的水。 每次你完成",
    ", which are like": "，就像",
    ", you unlock": "，你解锁",
    ", you will gain": "，你将获得",
    "! Each Age gives you one": "！ 每个时代都会给你一个",
    ". Keeping your": "。 保持你的",
    ". This effect compounds with other clicking-related upgrades.": "。 此效果与其他与点击相关的升级相结合。",
    ". This effect compounds with other upgrades.": "。 这种效果与其他升级相结合。",
    "(You have this achievement.)": "（你有这个成就。）",
    "+0.1 Wood Progress per second for each Lumberjack": "每个伐木工人每秒 +0.1 木材产量",
    "30% more resource progress": "资源产量增加 30%",
    "Advancement Point.": "进阶点数。",
    "Advancement Points": "进阶点数",
    "after banging some stones together. Very impressive.": "将一些石头敲在一起之后。 非常令人印象深刻。",
    "Age": "时代",
    "Age Advancement Point": "时代进阶点",
    "Age Upgrades": "时代升级",
    "bar you will now carry": "你现在将携带的酒吧",
    "but better! Hover over them to see if any of them interest you.": "但更好！ 将鼠标悬停在它们上方，看看其中是否有您感兴趣的。",
    "By using a solid cart, you can carry more wood back to your storage. Each time you complete the": "通过使用实心推车，您可以将更多木材运回仓库。 每次您完成",
    "capacity increases by": "容量增加",
    "Caveman": "穴居人",
    "clicking to gather resources": "点击收集资源",
    "cost reduction on all upgrades. This does not apply to": "降低所有升级的成本。 这不适用于",
    "Each time you advance to a new": "每次你前进到一个新的",
    "Enter the": "输入",
    "Exercising restraint will pay off in the long run. Applies a": "从长远来看，保持克制将会带来回报。 适用于",
    "for later, or buying the ones from previous ages are both valid strategies.": "供以后使用，或者购买以前的版本都是有效的策略。",
    "Further unlocks your untapped potential. You can now gain": "进一步释放您未开发的潜力。 您现在可以获得",
    "It's getting harder to store all that wood, you'll need to do something about it. Each shed will increase your maximum capacity for wood by": "储存所有木材变得越来越困难，你需要采取一些措施。 每个棚子都会增加你的木材最大容量",
    "Major civilizational breakthrough that will grant": "重大文明突破将赋予",
    "more": "更多的",
    "more resources when completing a": "完成任务时获得更多资源",
    "New Research: Mining": "新研究：采矿",
    "One of your lumberjacks noticed a cave in the forest. By clearing the area, you will have access to start mining from it. This also grants you": "你的一位伐木工人注意到森林里有一个洞穴。 通过清理该区域，您将可以从中开始采矿。 这也让你",
    "per click!": "每次点击！",
    "Progress Bar": "进度条",
    "Putting your woodworking skills to the task would allow you to build a container for all that water you're accumulating. Your maximum": "将你的木工技能运用到这项任务中，你可以建造一个容器来容纳你积累的所有水。 你的最大",
    "Stone Age": "石器时代",
    "storage capabilities for": "存储能力",
    "Temperance": "节制",
    "The Dominion of Assyria has entered the": "亚述帝国已进入",
    "This advancement costs": "此进阶成本",
    "This wonderful invention will allow you to gather": "这个奇妙的发明将让你收集",
    "to purchase": "购买",
    "Unlock your untapped potential. You can now gain": "释放您未开发的潜力。 您现在可以获得",
    "Water, every time you complete the": "水，每次完成时",
    "Water.": "水。",
    "Wheel": "车轮",
    "when": "什么时候",
    "which allows you to research special upgrades. Advancing to a new age also unlocks Major Upgrades and other bonuses that drastically improve your life. The": "它允许您研究特殊升级。 进入新时代还可以解锁重大升级和其他奖励，从而极大地改善您的生活。 这",
    "will lead to these changes:": "将导致这些变化：",
    "with every level of this upgrade.": "此升级的每个级别。",
    "Wow that bucket is useful! You should make a better one. Instead of": "哇，这个桶很有用！ 你应该做一个更好的。 代替",
    "You can use": "您可以使用",
    "You reached the": "您已到达",
    "You have this advancement.": "你已经有了这个进阶。",
    "Equip your lumberjacks with better axes. This will boost their current gathering rate by": "为您的伐木工配备更好的斧头。 这将提高他们当前的采集率",
    "per second.": "每秒。",
    "Sharper Axes": "更锋利的斧头",
    ", but increases the amount of": "，但增加了数量关于",
    ", but will cost you": "，但会花费你",
    ". Also increases your maximum": "。 还可以增加你的最大",
    "A heavier axe. Increases the amount of": "更重的斧头。 增加数量对于",
    "A heavier bucket. Increases the amount of": "一个更重的桶。 增加数量对于",
    "A stone pickaxe. Your technology is increasing at a tremendous rate. Increases the amount of": "一把石镐。 你们的技术正在以惊人的速度增长。 增加数量对于",
    "Allows your miners to drag the stone out of the mine at a quicker pace. With this, your miners will gather": "允许您的矿工以更快的速度将石头拖出矿井。 这样，你的矿工就会聚集起来",
    "as alternatives.": "作为替代方案。",
    "at an additional rate of": "以一个额外速率",
    "by": "",
    "capacity by": "容量",
    "have a constant cost to some resources. Be sure to read their descriptions before buying them.": "某些资源的成本是恒定的。 购买前请务必阅读其说明。",
    "in. Every level of your dam will give you": "你的大坝的每一层都会给你",
    "it takes to gather": "需要聚集",
    "on your maximum capacity for": "容量上限对于",
    "Poor souls are meant to toil away their life in a dark desolate place. Such a worker gives you": "可怜的灵魂注定要在黑暗荒凉的地方辛苦劳作。 这样的工人给你",
    "Researching this will allow you to make buildings. It seems like something worth looking into...": "研究这个将使你能够建造建筑物。 这似乎是值得研究的东西......",
    "Some resources are not always worth clicking your way through. Try to look for": "有些资源并不总是值得您点击浏览。 尝试寻找",
    "Start digging a dam to contain": "开始挖掘大坝以遏制",
    "Stone": "石头",
    "Stone Axe": "石斧",
    "Stone Bucket": "石桶",
    "Stone Pickaxe": "石镐",
    "you get by": "你获得了",
    "and for": "和",
    "Wooden Storage": "木制仓库",
    "A small enclosure for the sole purpose of storing resources. This will increase your maximum capacity for": "仅用于存储资源的小外壳。 这将增加您的最大容量对于",
    ", but they typically bypass the": "，但它们通常会绕过",
    "A structure that processes water your way. This will grant you a rate of": "按照您的方式处理水的结构。 这将为您提供以下比率",
    "are similar to": "类似于",
    "by directly giving raw resources. Therefore the rate should not be the only thing to consider when deciding whether to buy a worker or a building.": "通过直接提供原始资源。 因此，在决定是否购买工人或建筑物时，利率不应是唯一要考虑的因素。",
    "Water Mill": "水磨坊",
    ", but costs": "，但成本",
    "! Your workers now form a caste of self-ruling organizations which you oversee. This represents a major leap in innovation and will lead to several changes such as:": "！ 你的工人现在组成了一个由你监督的自治组织阶层。 这代表了创新的重大飞跃，并将带来一些变化，例如：",
    ". Mercy mild upon your kingdom.": "。 怜悯你的王国。",
    ". This effect stacks with other worker cost reductions.": "。 这种效果与其他工人成本的降低相叠加。",
    "+0.4 Wood Progress per second for each Lumberjack": "每个伐木工每秒 +0.4 木头产量",
    "+0.5 Stone Progress per second for each Miner": "每个矿工每秒 +0.5 石头产量",
    "+0.5 Water Progress per second for each Water Fetcher": "每个取水器每秒 +0.5 水产量",
    "A refinery to produce": "炼油厂生产",
    "A site that extracts": "一个可以提取的网站",
    "A structure for your workers to labor away in. Each": "供您的工人在其中工作的结构。每个",
    "Additional Advancements": "额外的进阶",
    "Advances in storage technologies allows you to increase your storage of": "存储技术的进阶使您可以增加存储空间",
    "ahead of time so you know which resources' rates to improve upon. Buying the first available": "提前了解哪些资源的费率需要改进。 购买第一个可用的",
    "cost reduction to": "成本降低至",
    "directly. Each": "直接地。 每个",
    "Discover new ways to extract Stone by yourself. You can now gain": "探索自己提取石头的新方法。 您现在可以获得",
    "Equestrianism": "马术",
    "Feudal Age": "封建时代",
    "in the": "在",
    "Lead the way for your faithful and be rewarded with their devotion. Gain a": "为您的忠实信徒引路，并获得他们的奉献精神的回报。 获得一个",
    "Lord": "勋爵",
    "may not always be the answer.": "可能并不总是答案。",
    "Monarchy": "君主制",
    "New Resource: Iron": "新资源：铁",
    "Next Age": "下一个时代",
    "per level.": "每级。",
    "Piety": "虔诚",
    "Plan your": "计划你的",
    "Printing Press": "印刷机",
    "Progress": "进度",
    "Republic of Russia": "俄罗斯共和国",
    "required for resources as follows:": "所需资源如下：",
    "Sawmill": "锯木厂",
    "Stone Quarry": "采石场",
    "The Republic of Russia has entered the": "俄罗斯联邦已进入",
    "They will be talking about you in history books now. You can now gain": "他们现在将在历史书上谈论你。 您现在可以获得",
    "This unique invention will not provide immediate benefits to you, but it will pave the way to the future. Unlocks": "这项独特的发明不会为您带来立竿见影的好处，但它将为未来铺平道路。 解锁",
    "to operate it.": "来操作它。",
    "Vassalism": "附庸主义",
    "Water Fetchers": "取水器",
    "will gather by": "将聚集在",
    "will increase production of": "将增加产量",
    "with minimum effort. Each": "以最小的努力。 每个",
    "With some experimentation, you manage to craft what looks like bigger versions of water buckets. Your": "通过一些实验，你可以制作出看起来更大的水桶。 你的",
    "Wooden Basin": "木盆",
    "Your unparalleled ability to tame nature around you leads to increased benefits. Reduce the amount of": "您驯服周围自然的无与伦比的能力会带来更多的好处。 减少用量",
    ", these workers will work tirelessly, providing you a bonus of": "，这些工人将不知疲倦地工作，为您提供奖金",
    "A heavy sickle to greatly improve your farming. Increases the amount of": "一把重型镰刀，可以极大地改善你的耕作。 增加量",
    "Agriculture": "农业",
    "All Workers": "所有工人",
    "bar is completed.": "酒吧已完成。",
    "Delegate your resource management to trusty vassals. As a result of their loyalty, your economy grows at an accelerated pace, allowing you to buy workers for cheaper. Reduces the cost of": "将您的资源管理委托给值得信赖的附庸。 由于他们的忠诚度，您的经济增长速度加快，使您能够以更便宜的价格购买工人。 降低成本",
    "Entrench your castle with solid foundations. Mostly it just looks nice, but it will also allow you to store:": "用坚实的地基来巩固你的城堡。 大多数情况下，它只是看起来不错，但它还允许您存储：",
    "every time you the": "每次你",
    "Foundations": "基础",
    "in your keep. This will help you prosper.": "在你的掌控中。 这将帮助您繁荣。",
    "Iron": "铁",
    "Ironsmith": "铁匠",
    "The scale and scope of your economy is visibly growing by the day. Allows you to collect": "你们的经济规模和范围日益明显扩大。 让您可以收集",
    "Wheat": "小麦",
    ". This effect stacks with the": "。 该效果与",
    "After much research, your workers come up with ways to improve your resource generation. Fundamentally redesign your": "经过大量研究后，您的工作人员想出了改善资源生成的方法。 从根本上重新设计您的",
    "An even heavier axe. Increases the amount of": "更重的斧头。 增加量",
    "An even heavier bucket. Increases the amount of": "更重的桶。 增加量",
    "An even heavier pickaxe. Increases the amount of": "更重的镐。 增加量",
    "each.": "每个。",
    "in exchange for a benefit of": "以换取某种利益",
    "Increased literacy rates among your workers allows them to develop more advanced techniques. Gain": "工人识字率的提高使他们能够开发更先进的技术。 获得",
    "Iron Axe": "铁斧",
    "Iron Bucket": "铁桶",
    "Iron Pickaxe": "铁镐",
    "Literacy": "识字能力",
    "Outer Québec has entered the": "外魁北克省已进入",
    "to add a cost of": "添加成本",
    "Water Mills": "水磨坊",
    ", as well as collect dues from Farmers throu": "，以及通过以下方式向农民收取会费",
    ". Your": "。 你的",
    "an additional rate of": "额外费率",
    "and each": "和每个",
    "Establish law and order through your wise kingship. Enables you to hire": "通过你明智的王权建立法律和秩序。 使您能够雇用",
    "Ironsmiths": "铁匠",
    "Miners": "矿工",
    "will produce an additional": "将产生额外的",
    "You learn to care for the forest to get more from its resources in the long run. Grants each": "从长远来看，您要学会照顾森林，以便从其资源中获得更多。 补助金每",
    "Your newer tools allow you to dig deeper into the earth to extract more water. Grants each": "您的新工具可以让您更深地挖掘地球以提取更多的水。 补助每个",
    ", as well as collect dues from Farmers through": "，以及通过以下方式向农民收取会费",
    "All Buildings": "所有建筑",
    "will cost": "将会花费",
    "Your advanced understanding of building allows you to save on construction costs. By purchasing this upgrade,": "您对建筑的深入了解可以帮助您节省建筑成本。 通过购买此升级，",
    ", but cost": "，但成本",
    ". However, it will increase their cost by": "。 然而，这会增加他们的成本",
    ". Will also add": "。 还会添加",
    "Apprenticeship": "学徒制",
    "cost of each": "的成本对于每个",
    "Farmers are an important workforce you likely couldn't do without. Each Farmer will supply": "农民是您可能离不开的重要劳动力。 每个农民将提供",
    "Irrigation": "灌溉",
    "Mitigate the necessity to provide Water to your Farmers. This upgrade will reduce the": "减轻向农民提供水的必要性。 此次升级将减少",
    "More Worker Types": "更多工人类型",
    "Nourishment": "营养",
    "The process of digging channels to help water flow through your fields turns your labor into more plentiful crops. Increases the production rate of": "挖掘渠道以帮助水流过田地的过程可以将您的劳动转化为更丰富的农作物。 提高生产率",
    "Through refining the arts of the trade, your more experienced workers can watch over apprentices for various benefits. Provides you with": "通过完善交易艺术，经验丰富的工人可以照顾学徒以获得各种好处。 为您提供",
    "to purchase. Will also increase your maximum capacity for": "购买。 还将增加您的最大容量",
    "to your Wheat maximum storage capacity.": "到您的小麦最大存储容量。",
    ", which is useful for buying various things. Everything is about to change...": "，这对于购买各种东西很有用。 一切都即将改变……",
    "; even better, you can now collect": "; 更好的是，您现在可以收集",
    "! Your population is struck with disease due to overall lack of hygiene. This causes the first economic crisis which you must go through in order to survive. The effects of advancing to this age are negative but lead to better days. The": "！ 由于整体缺乏卫生条件，您的人口遭受疾病侵袭。 这导致了第一次经济危机，你必须经历这场危机才能生存。 提前到这个年龄的影响是负面的，但会带来更好的日子。 这",
    ". Each": "。 每个",
    ". This effect stacks with other building cost reductions.": "。 这种效果与其他建筑成本的降低相叠加。",
    ". This makes water fetchers significantly cheaper.": "。 这使得取水器的成本大大降低。",
    "A growing expertise in the art of processing iron allows you to make the process more efficient. Grants each": "不断增长的铁加工技术专业知识使您能够提高流程效率。 补助金每",
    "A steadfast attitude and unwavering resolve can help you brave any storm. Applies a": "坚定的态度和坚定不移的决心可以帮助你勇敢地面对任何风暴。 适用于",
    "As useful as it is necessary for the heavy production of": "对于大量生产来说很有用",
    "Both a recluse and a nature lover, forresters repopulate forests through their care and patience. Each Forrester provides you with": "福雷斯特人既是隐士，又是自然爱好者，通过他们的细心和耐心，让森林重新繁衍生息。 每个 福雷斯特人 为您提供",
    "building which will toll your workers but provide resources in exchange.": "建造这栋建筑会让你的工人付出代价，但会提供资源作为交换。",
    "by holding the ctrl key before clicking on their respective button.": "在单击各自的按钮之前按住 ctrl 键。",
    "Church": "教会",
    "Construct small iron baskets to hold resources in. Adds an additional": "建造小铁篮来存放资源。添加额外的",
    "Dark Age": "黑暗时代",
    "Dark Times": "黑暗时代",
    "Dark Times Ahead...": "黑暗时代即将来临……",
    "Demonstrate your willingness to go on. Your": "表现出你继续下去的意愿。 你的",
    "Expertly curating and milling stones allows you to keep even more of them than you previously thought possible. Grants each": "熟练地整理和铣削石头可以让您保留比您以前想象的更多的石头。 补助金每",
    "Fervor": "热情",
    "Find your green thumb. You can now gain": "找到你的园艺技能。 您现在可以获得",
    "for each": "对于每个",
    "Forrester": "福雷斯特人",
    "Foundries": "铸造厂",
    "Gold": "黄金",
    "Grain Mill": "谷物磨坊",
    "Iron Will": "钢铁意志",
    "Lanterns": "灯笼",
    "Commerce": "商业",
    "Miller": "磨坊工人",
    "New Building: Grain Mill": "新建筑：谷物磨坊",
    "no longer cost any": "不再花费任何费用",
    "Organize a large harvest distribution to boost the morale of your workers. Increases the production rate of each": "组织一次大规模的收获分配，以提高工人的士气。 提高每件产品的生产率",
    "Propagate your ideals to your population swiftly by appointing chosen preachers to guide the masses. Adds a": "通过任命选定的传教士来指导群众，将您的理想迅速传播给您的人民。 添加一个",
    "purchased by": "购买者",
    "Somewhat of a jack-of-all-trades, millers are crafty workers providing their own aspecy of the economy. Each Miller provides you with": "磨坊工人是多才多艺的人，他们是狡猾的工人，为经济提供了自己的特色。 每个磨坊工人为您提供",
    "Stone Storage": "石头储存",
    "The lack of available resources forces you to improvise. Reduce the cumulative cost increase rate of": "缺乏可用资源迫使您即兴发挥。 降低累计成本增长率",
    "Through the development of commerce, you find out the use of bartering for good, allowing you to perform": "随着商业的发展，你发现了以物易物的用途，可以让你执行任务",
    "to operate. This does not affect their current production rate.": "来操作。 这并不影响他们目前的生产率。",
    "to the maximum capacity of": "至最大容量",
    "You can sell": "你可以卖",
    "Your potential is finally being achieved. You can now gain": "你的潜力终于得到了发挥。 您现在可以获得",
    "Your understanding of architecture increases further, allowing you to save on construction costs. By purchasing this upgrade,": "您对建筑的理解进一步加深，从而可以节省建筑成本。 通过购买此升级，",
    ", as well as facilitate your existing mining projects. Reduce the total": "，以及促进您现有的采矿项目。 减少总量",
    ", your": "， 你的",
    ". This makes water mills significantly cheaper.": "。 这使得水磨坊的成本大大降低。",
    "A large stone enclosure for the sole purpose of storing resources. This will increase your maximum capacity for": "一个巨大的石头围场，其唯一目的是储存资源。 这将增加您的最大容量",
    "Allow your miners to carry light with them for long expeditions in the dark. This makes them feel better. Reduces the resource upkeep of": "让您的矿工携带照明设备，在黑暗中进行长时间探险。 这让他们感觉更好。 减少资源维护",
    "are exchanges of goods that can be repeatedly done to stimulate your economy. Some trades will require resources, other gold, or a mix of both. Make sure to have a look at the available trades when struggling with a particular resource.": "是可以重复进行的商品交换，以刺激经济。 有些交易需要资源、其他黄金或两者的混合。 当遇到特定资源的困难时，请务必查看可用的交易。",
    "Become the ultimate harvester. You can now gain": "成为终极收割机。 您现在可以获得",
    "by 50.": "50。",
    "Farmers": "农民",
    "in exchange for": "换取",
    "Persuade some of your people to work harder for you. Grants each": "说服你的一些人为你更加努力地工作。 补助金每",
    "required to gather": "需要聚集",
    "rest after a long day at work. This will greatly help with their overall productivity. Increases the production rate of each": "经过一整天的工作后休息。 这将极大地提高他们的整体生产力。 提高每件产品的生产率",
    "Silver": "银",
    "Start building farmhouses to help your": "开始建造农舍来帮助你",
    "Stone Quarries": "采石场",
    "Stone to Iron": "用石头换铁",
    "The lack of available resources forces you to improvise further. Reduce the cumulative cost increase rate of": "缺乏可用资源迫使您进一步即兴发挥。 降低累计成本增长率",
    "This new excavation technique will allow you to reach for": "这种新的挖掘技术将让您能够到达",
    "Trade": "交易",
    "Water to Wood": "用水换木头",
    "Wheat to Water": "用小麦换水",
    "Wood to Stone": "用木头换石头",
    ", who will build up": "，谁来建立",
    "! Will also allow you to hire": "！ 还将允许您雇用",
    "A shiny axe. Increases the amount of": "一把闪亮的斧头。 增加量",
    "A shiny bucket. Increases the amount of": "一个闪亮的桶。 增加量",
    "A shiny pickaxe. Increases the amount of": "一把闪亮的镐。 增加量",
    "A shiny sickle. Increases the amount of": "一把闪亮的镰刀。 增加量",
    "Allows you to hire": "允许您雇用",
    "Farm Hands": "农场帮手",
    "for you. Time to harness this new resource.": "为你。 是时候利用这个新资源了。",
    "Further facilitates your existing mining projects. Reduce the total": "进一步促进您现有的采矿项目。 减少总量",
    "Gain access to more advanced": "获得更高级的访问权限",
    "Iron to Silver": "用铁换银",
    "Reinforce the foundations of your quarries. Reduces the resource upkeep of": "加固采石场的地基。 减少资源维护",
    "Silver Axe": "银斧头",
    "Silver Bucket": "银桶",
    "Silver Progress": "银产量",
    "Silver Sickle": "银镰刀",
    "Silversmith": "银匠",
    "Silversmiths": "银匠",
    "to help your economy withstand the hardships of the times. Your advisors came up with brilliant strategies to do so.": "帮助您的经济经受住时代的考验。 您的顾问为此想出了绝妙的策略。",
    "from mines. Each Silversmith will supply": "来自矿山。 每个银匠都会提供",
    "Specialized worker who excels in the art of getting": "擅长获取艺术的专业工人",
    "Load": "加载",
    "Paste the export string here:": "将导出的存档字符串粘贴到此处：",
    "Breakthrough in technology allows you to extract much more Iron. You can now gain": "技术的突破可以让您提取更多的铁。 您现在可以获得",
    "Reach levels of productivity previously thought impossible. You can now gain": "达到以前认为不可能的生产力等级。 您现在可以获得",
    ". This makes lumberjacks significantly cheaper.": "。 这使得伐木工的成本大大降低。",
    "A less useful and wimpier-looking version of a farmer. Has its uses. Each Farm Hand provides you with": "一个不太有用、看起来更懦弱的农民版本。 有它的用处。 每个农场帮手都会为您提供",
    "Advancement Point": "进阶点数",
    "Another shiny pickaxe. Increases the amount of": "又一把闪亮的镐。 增加量",
    "at the cost of": "的成本为",
    "Boots": "靴子",
    "Farm Hand": "农场帮手",
    "Gloves": "手套",
    "is worth the trouble!": "值得麻烦！",
    "Millers": "磨坊工人",
    "Property Tax": "财产税",
    "Provide Boots for your workers to ease their burden. Reduces resource upkeep of": "为您的工人提供靴子以减轻他们的负担。 减少资源维护",
    "Provide Gloves for your workers to ease their burden. Reduces resource upkeep of": "为您的工人提供手套以减轻他们的负担。 减少资源维护",
    "Silver to Gold": "用银换黄金",
    "Start massively stocking up on resources. Increases the maximum capacity of": "开始大量储备资源。 增加最大容量",
    "Tax": "税",
    "The lack of available resources forces you to improvise ever more. Reduce the cumulative cost increase rate of": "可用资源的缺乏迫使你更多地即兴发挥。 降低累计成本增长率",
    "trades.": "交易。",
    "Try to balance your ratio of workers-to-buildings to get the most out of your": "尝试平衡工人与建筑物的比例，以充分利用您的资源",
    "per": "每个",
    ". Best of luck in this upcoming trial.": "。 祝您在即将到来的审判中好运。",
    ". Each point costs more": "。 每个点数花费更多",
    ". The collected amount can never go below 0.": "。 收集的金额永远不会低于 0。",
    "Building": "建筑",
    "Currently you have:": "目前您有：",
    "Oh brave one, you have reached the": "噢，勇敢的人，你已经到达了",
    "Purchase an": "购买一个",
    "Tax your population via the properties. Collect": "通过财产向你的人口征税。 收集",
    "Tax your population. Collect": "对你的人口征税。 收集",
    "than the last.": "比上次。",
    "you have. However, doing so will incur a welfare cost of": "你有。 然而，这样做会产生一定的福利成本",
    "you have. However, doing so will incur an upkeep cost of": "你有。 然而，这样做会产生维护成本",
    "! With the endured hardships, your people develop deeper understanding of the world around them, leading to a revolution in their thinking. The": "!在经历了苦难之后，你们的人民对周围的世界有了更深入的了解，从而导致了他们的思维革命。 这",
    "Age of Renaissance": "文艺复兴时期",
    "Colonies": "殖民地",
    "New Building: Jewelry": "新建筑：珠宝",
    "New Resource: Diamond": "新资源：钻石",
    "One more shiny pickaxe. Increases the amount of": "又一把闪亮的镐。 增加数量",
    "Renaissance": "文艺复兴",
    ", at the cost of": "，成本为",
    ". Doing so means you will have to start from scratch, but you will be allowed to carry over": "。 这样做意味着您必须从头开始，但您将被允许继承",
    ". Prestige points can be used to purchase permanent bonuses that stick from colony to colony.": "。 声望点可用于购买永久奖励，这些奖励会在各个殖民地之间持续存在。",
    "50% more resource progress": "资源进度增加 50%",
    "A fine black powder that reacts strongly when ignited. Thanks to this technological wonder,": "一种细小的黑色粉末，点燃时会发生强烈反应。 得益于这一技术奇迹，",
    "Additional Trades": "额外交易",
    "Advanced understanding of mathematical principles begin to arise in your population, paving the way to future improvements.  Applies a": "你们的人群开始对数学原理有了深入的理解，为未来的进步铺平了道路。 适用于",
    "Advancement Points.": "进阶点数。",
    "and increase the max capacity of": "并增加最大容量",
    "Aqueducts": "渡槽",
    "as you create more colonies.": "当你创建更多的殖民地时。",
    "Better care for the forest yields an increased productivity in the long run. Every": "从长远来看，更好地照顾森林可以提高生产力。 每一个",
    "Better Foundries": "更好的铸造厂",
    "Breakthrough in technology allows you to extract much more Silver. You can now gain": "技术的突破可以让您提取更多的银。 您现在可以获得",
    "by a rate of": "的比率为",
    "clicking to gather a resource": "单击以收集资源",
    "Colony": "殖民地",
    "deeper in the forest to reach finer timber that grants additional resources. This increases their production by": "深入森林以获得更优质的木材，从而获得更多资源。 这增加了他们的产量",
    "Designed with the ambition to produce silver through less effort than manual extraction. Each": "其设计目标是通过比手动提取更少的努力来生产银。 每个",
    "Diamond": "钻石",
    "for each level purchased.": "对于购买的每个级别。",
    "for your next colony.": "为了你的下一个殖民地。",
    "gains an increase in productivity of": "生产力提高",
    "Gunpowder": "火药",
    "Have a second look at the design of your foundries to spot any improvements that could be made. Grants each": "再次审视铸造厂的设计，找出可以改进的地方。 补助金每",
    "increases production of": "增加产量",
    "Innovative mining techniques allow your": "创新的采矿技术让您",
    "Invest in recreating technology from the past to perfect your current water systems. Increases the production of each": "投资重建过去的技术来完善您当前的供水系统。 增加每一个的产量",
    "Jewelry": "珠宝",
    "Logos": "标志",
    "Lumberjacks": "伐木工",
    "Major development in commerce allows you to perform": "商业的重大发展使您能够执行",
    "Mathematics": "数学",
    "menu allows you to set out and leave your civilization behind in favor of building a": "菜单允许你出发并将你的文明抛在身后，以建立一个",
    "menu. Give it a try!": "菜单。 试一试！",
    "Mercantilism": "重商主义",
    "Prestige Point": "声望点数",
    "Prestige Points": "声望点数",
    "Proper management of water usage on farms lowers the amount of wasted water every harvest season. Reduces the upkeep of each": "正确管理农场的用水量可以减少每个收获季节的废水量。 减少每一个的维护",
    "Pure Greed": "纯粹的贪婪",
    "required to extract": "需要提取",
    "Restraint": "克制",
    "Scholar": "学者",
    "Secret Upgrades": "秘密升级",
    "Send your": "发送你的",
    "Silver Mastery": "银精通",
    "Silver to Diamond": "用银换钻石",
    "The further you go with your civilization, the more": "你的文明走得越远，就越",
    "The more": "越多",
    "to manipulate the market to your advantage.": "操纵市场以对您有利。",
    "to work at an increased efficiency. Increase their work rate by": "以提高工作效率。 提高他们的工作效率",
    "to work at their current rate.": "以目前的速度工作。",
    "Total mastery over the art of silverwork allows you to significantly speed up the production of the shiny metal. Decreases the": "完全掌握银制品艺术可以让您显着加快闪亮金属的生产速度。 减少",
    "Turn your farms into vastly superior investments. Each": "将您的农场变成极其优质的投资。 每个",
    "will be granted when": "将被授予时",
    "with an additional gain of": "额外增益为",
    "you build, the faster you get at reaching the next colony. On top of that, you may also discover": "你建造的越多，到达下一个殖民地的速度就越快。 除此之外，您可能还会发现",
    "You can change the look of the interface by changing the current": "您可以通过更改当前的界面来更改界面的外观",
    "You feel invigorated by the prospect of settling into a colony, away from the complexity of your now powerful empire. By researching this upgrade, you gain": "远离现在强大帝国的复杂性，定居在殖民地的前景让你感到振奋。 通过研究此升级，您将获得",
    "you gain. It's all about finding the right balance between progressing further and starting a new colony!": "你获益。 这一切都是为了在进一步进步和建立新殖民地之间找到适当的平衡！",
    "Your use of reason grows through practice of the mind. After shedding their earthly needs, your": "你对理性的运用会通过头脑的练习而增长。 在摆脱了尘世的需求之后，你的",
    "also gains an increase of": "也获得了增加",
    "and the amount of": "以及数量对于",
    "Exercise greater control over resource gathering. Reduces the amount of": "对资源收集实行更大的控制。 减少数量",
    ", as well as": "， 以及",
    ": these workers will generate a smaller amount of": "：这些工人将产生较少量的",
    "and increases the amount of": "并增加量",
    "Better Mills": "更好的磨坊",
    "but at a lesser cost.": "但成本较低。",
    "Diamond Axe": "钻石斧",
    "Diamond Bucket": "钻石桶",
    "Diamond Sickle": "钻石镰刀",
    "Diamond Trade": "钻石交易",
    "Gold for Diamond": "用黄金换钻石",
    "Diamond for Gold": "用钻石黄换金",
    "Have a second look at the design of your mills to spot any improvements that could be made. Grants each": "再次审视工厂的设计，找出可以改进的地方。 补助金每",
    "Jewelers": "珠宝商",
    "Open new trade routes to get value from diamonds. Allows you to trade": "开辟新的交易路线以从钻石中获取价值。 让您可以进行交易",
    "than": "比",
    "The shiniest of all axes. Increases the amount of": "所有轴中最闪亮的。 增加数量",
    "The shiniest of all buckets. Increases the amount of": "所有桶中最闪亮的。 增加数量",
    "The shiniest of all pickaxes. Increases the amount of": "所有镐中最闪亮的。 增加数量",
    ". Also allows you to start building": "。 还允许您开始构建",
    "Clarity": "明晰",
    "Diamond to Gold": "用钻石换黄金",
    "Diamonds": "钻石",
    "Extractors": "提取器",
    "from the earth.": "来自地球。",
    "Gold to Diamond": "用黄金换钻石",
    "increases their production by": "增加他们的产量",
    "Jeweler": "珠宝商",
    "The shiniest of all shiny pickaxes. Increases the amount of": "所有闪亮镐中最闪亮的。 增加量",
    "The shiniest of all sickles. Increases the amount of": "所有镰刀中最闪亮的。 增加量",
    "to pull": "拉",
    "Your increasing knowledge towards and expert handiwork out of silver veins prove useful. Each": "你对银矿不断增长的知识和专家的手工技艺证明是有用的。 每个",
    "Your wisdom grows with each passing moment. Increases your resources gathered when completing a": "你的智慧随着每一刻的流逝而增长。 增加完成任务时收集的资源",
    "All that glitters is not gold...": "闪光的不一定都是金子...",
    "Glitters": "闪光",
    "In more peaceful and prosperous times, the strangest of professions arise. Every Jeweler provides you with": "在更加和平和繁荣的时代，最奇怪的职业出现了。 每个珠宝商都为您提供",
    ". What else is money good for, really?": "。 钱真的还有什么用呢？",
    ". You should be proud.": "。 你应该感到骄傲。",
    "(before passive increases). Stop this madness.": "（被动增加之前）。 停止这种疯狂吧。",
    "Achievement Point": "成就点",
    "for a profit of": "以获取利润",
    "for an": "对于一个",
    "One or more Trades were made this colony.": "这个殖民地进行了一项或多项交易。",
    "You conducted a": "您进行了一次",
    "You lead your realm to the age of the": "你带领你的王国进入了",
    "You traded": "你交易了",
    ", as well as the amount of": "，以及数量",
    "! Each miner will start digging for": "！ 每个矿工都会开始挖掘",
    "Diamond Progress": "钻石产量",
    "Extractor": "提取器",
    "The peak of storage technology. Upgrades the maximum capacity of": "存储技术的巅峰。 升级最大容量",
    "The shiniest of all shiniest pickaxes. Increases the amount of": "所有最闪亮的镐中最闪亮的。 增加量",
    "The ultimate shiny pickaxe. Increases the amount of": "终极闪亮镐。 增加量",
    "to gather": "收集",
    "Your mining technology now allows your": "您的采矿技术现在可以让您",
    "built increases": "建成增加",
    "Lower the upkeep of your buildings when collecting taxes from your population. Your": "向居民征税时降低建筑物的维护费用。 你的",
    "production by": "生产",
    "Seek out diamonds deep into the core of the earth. Each": "寻找深入地心的钻石。 每个",
    "trade cost per building is reduced by": "每栋建筑的交易成本减少",
    "Through cunning trade and craftmanship, you reap the rewards of your past hard work. This upgrade grants you": "通过狡猾的贸易和工艺，你会收获过去辛勤工作的回报。 此次升级为您提供",
    "but will provide a gain to the raw resources at a rate of": "但会以一定比例增加原始资源",
    "Extend the peak of storage technology to other resources. Upgrades the maximum capacity of": "将存储技术的巅峰扩展到其他资源。 升级最大容量",
    "Quintessential civilizational landmark. Will toll the Progress of your": "典型的文明地标。 将会影响你的进步",
    ". Additionally grants": "。 额外补助",
    "Advanced architectural studies drastically renew your ability to mitigate construction costs. By purchasing this upgrade,": "高级建筑研究极大地提高了您降低建筑成本的能力。 通过购买此升级，",
    "": "",
    "also gains an additional": "还额外获得",
    "": "",
    "You can disable these tips by switching the tutorial off in the Settings.": "您可以通过在“设置”中关闭教程来禁用这些提示。",
    "! Unrest grows in your population and the people yearn for change. This will come at a cost, but perhaps you can make the endeavour worthwile with some patience. The": "！ 你们的人口中的骚乱不断增加，人们渴望变革。 这是有代价的，但也许你可以通过一些耐心让努力变得值得。 这",
    "10% Worker Cost Increase": "工人成本增加 10%",
    "15% Building Cost Increase": "建筑成本增加 15%",
    "Age of Revolution": "变革时代",
    "Increased Silver Cost of Taxes": "白银税收成本增加",
    "Pumping System passive bonus (+10 Water": "抽水系统被动奖励（+10 水",
    "to purchase this upgrade.": "购买此升级。",
    "You need to have built at least": "你需要至少建造",
    "and architecture come naturally to you. Reduces the cost of all": "建筑对你来说是自然而然的。 降低了大家的成本",
    ", instead of being reset to zero, the value past the maximum is": "，超过最大值的值不是重置为零，而是",
    ". If the bar would be filled more than once by the added value, resources are gathered more than once.": "。 如果该条会被附加值多次填充，则资源会被多次收集。",
    "(cumulative) for each level purchased.": "（累计）购买的每个级别。",
    "+0.5 more Water Progress per click": "每次点击 +0.5 更多水进度",
    "+0.5 more Wheat Progress per click": "每次点击增加 0.5 小麦进度",
    "+1 more Wood Progress per click": "每次点击 +1 更多木材进度",
    "+1 Water, Wood and Stone": "+1 水、木头和石头",
    "+2 more Stone Progress per click": "每次点击 +2 更多石头进度",
    "0% Base Click Power": "0% 基本点击功率",
    "0% Progress Completion Multiplier": "0% 进度完成乘数",
    "1% Progress Completion Multiplier": "1% 进度完成乘数",
    "2% Base Click Power": "2% 基本点击力",
    "A bit of creativity goes a long way. Increases the cost of": "一点创造力会有很大帮助。 增加了成本",
    "additional Advancement": "额外进步",
    "advancement available for purchase now and at the start of every colony.": "现在和每个殖民地开始时都可以购买进步。",
    "an additional Leader": "额外的领导者",
    "AND": "和",
    "any resource. Auto-clicking will occur every": "任何资源。 每隔一段时间就会发生自动点击",
    "Are you sure you want to start a new colony? Your progress will be reset, however you will be allowed to keep the following:": "您确定要开始一个新的殖民地吗？ 您的进度将被重置，但您可以保留以下内容：",
    "as well as": "也",
    "Attain mastery in the manipulation of fire. Automatically acquires the": "掌握火的操纵。 自动获取",
    "Automatically gather": "自动采集",
    "Base Click Power": "基本点击功率",
    "Become a mighty leader of men through sheer charisma. Reduces the cost of all": "凭借纯粹的魅力成为强大的男性领袖。 降低了大家的成本",
    "Cancel": "取消",
    "carried over": "结转",
    "Carry some resources over to your new colonies to drastically speed up the early stage of rebuilding. Provides": "将一些资源转移到您的新殖民地，以大大加快重建的早期阶段。 提供",
    "Delve into the forbidden knowledge of agriculture. You get": "深入探究农业禁忌知识。 你得到",
    "Dominion": "统治",
    "double": "双倍的",
    "Each tax exerted on your population passively grants an additional": "对你的人口征收的每一项税收都会被动地给予你额外的",
    "each time a resource progress is completed, at the cost of": "每次完成资源进度时，代价为",
    "Excel in the art of precipitating the development of your colonies. Makes the": "擅长促进殖民地的发展。 使得",
    "Fire Advancement": "消防进步",
    "Focus on your mastery of the earth for increased specialized gains. You get": "专注于你对地球的掌握，以增加专业收益。 你得到",
    "Focus on your mastery of the forest for increased specialized gains. You get": "专注于对森林的掌握，以增加专业收益。 你得到",
    "Focus on your mastery of water for increased specialized gains. You get": "专注于对水的掌握，以增加专业收益。 你得到",
    "for each level.": "对于每个级别。",
    "for each level. The gain is added after calculating the final tax amount.": "对于每个级别。 计算最终税额后添加收益。",
    "for each purchased level.": "对于每个购买的级别。",
    "for every level acquired.": "对于获得的每个级别。",
    "for free.": "免费。",
    "from a future one to a present one. If you have no pending prestige points, the bonus is applied as soon as you acquire one.": "从未来的到现在的。 如果您没有待处理的声望点，则奖励将在您获得声望点后立即应用。",
    "Hold the mouse button down": "按住鼠标按钮",
    "in exchange of a": "以换取一个",
    "in order to": "为了",
    "in your next colony every level. This effect only applies once.": "在你的下一个殖民地的每个级别。 该效果仅适用一次。",
    "increase in base click power. Cumulates every level.": "增加基本点击力。 累积每个级别。",
    "Inspire even the lowest of workers to devote themselves to the common good. Each": "激励哪怕是最低层的工人致力于共同利益。 每个",
    "Learn from new experiences to grow stronger every time you settle a new colony. Gain": "每次定居新殖民地时，都会从新的经历中学习，变得更加强大。 获得",
    "Massively invest in heavy research to prop up every future colony with a significant starting advantage. Reveals and makes available for purchase the basic": "大量投资于大量研究，以支持每个未来的殖民地具有显着的起始优势。 揭示并提供基本的购买",
    "more resources every time you complete a": "每次完成任务都会获得更多资源",
    "more resources when completing a progress bar. Cumulates every level.": "完成进度条时获得更多资源。 累积每个级别。",
    "Nerves of steel are meant to withstand the storm. For each level, gain an additional": "钢铁般的意志是为了抵御风暴。 对于每个级别，获得额外的",
    "No time to waste. For every colony, converts a": "没时间浪费。 对于每个殖民地，转换",
    "now and everytime you start a new colony.": "现在以及每次你开始一个新的殖民地时。",
    "of your base click power. This cumulates every level.": "您的基本点击力。 这会累积每个级别。",
    "of your base click power. Your current": "您的基本点击力。 您当前的",
    "of your current amount of": "您当前的金额",
    "per colony.": "每个殖民地。",
    "Prestige Point per level": "每级声望点",
    "Prestige Point.": "声望点。",
    "Prestige Points.": "声望点。",
    "provides an additional": "提供了额外的",
    "provides you:": "为您提供：",
    "Reckless actions can lead to a good outcome with proper insight. Decreases the resources gained when completing a progress bar by": "鲁莽的行动可以通过正确的洞察力带来良好的结果。 完成进度条时获得的资源减少",
    "Reduces the workload of iron gathering through unconventional methods. Each level increases the minimum threshold of": "通过非常规方法减少取铁工作量。 每个级别都会增加最低阈值",
    "Reduces the workload of stone gathering through unconventional methods. Each level increases the minimum threshold of": "通过非常规方法减少采石工作量。 每个级别都会增加最低阈值",
    "Reduces the workload of wood gathering through unconventional methods. Each level increases the minimum threshold of": "通过非常规方法减少木材采集的工作量。 每个级别都会增加最低阈值",
    "Requirements:": "要求：",
    "Resource Progress Bar": "资源进度条",
    "Revolution in resource progress tracking. When filling a": "资源进度跟踪的革命。 当填充一个",
    "Sharpen your understanding of overall structures for long-term benefits. Reduces the cumulative cost increase rate of": "加深您对整体结构的理解，以获得长期利益。 降低累计成本增长率",
    "Some are simply unable to let go of their hard-earned riches. When creating a new colony, keep": "有些人根本无法放弃他们辛苦赚来的财富。 创建新殖民地时，请保留",
    "Start a new colony?": "开始一个新的殖民地？",
    "Step by step, you get stronger and manage to carry more resources yourself. Your base clicking power increases by an additional": "一步一步地，你会变得更强，并能够自己携带更多的资源。 您的基本点击能力会额外增加",
    "Temporary setbacks can sometimes result in future profits. Does nothing now, but provides you with": "暂时的挫折有时可能会带来未来的利润。 现在什么都不做，但为您提供",
    "that affect your": "影响你的",
    "The art of weaponry unfolds itself to you, allowing you greater clicking powers than previously thought possible. Each level unlocks an": "武器的艺术向你展现，让你拥有比以前想象的更大的点击能力。 每个级别都会解锁一个",
    "The essence of inner strength resides in the wider variety of areas you can improve upon through perseverance. Each level grants you an additional": "内在力量的本质在于通过坚持不懈可以提高的更广泛的领域。 每个级别都会授予您额外的",
    "the resource progress gathered when you click. Double Clicking will occur every": "单击时收集的资源进度。 双击将会发生",
    "This mysterious artifact will occasionally boost your resource gathering. Will sometimes": "这个神秘的神器偶尔会促进你的资源收集。 有时会",
    "This prestige skill costs": "此声望技能需要花费",
    "This technological wonder will allow you to greatly facilitate resource gathering. Unlocks the ability to": "这项技术奇迹将让你极大地方便资源收集。 解锁以下能力：",
    "tied to the following ages:": "与以下年龄相关：",
    "to you.": "给你。",
    "You become proficient at arguing your way to victory. Reduces the overall cost of": "你会变得擅长通过辩论来取得胜利。 降低了总体成本",
    "Your ability to turn a profit from thin air is most impressive. Start each colony with the ability to make the following trades:": "你凭空获利的能力令人印象深刻。 每个殖民地开始时都能够进行以下交易：",
    "Your connections with the people reach far out wide, even to the outskirts of the forest. Each level provides": "你与人们的联系非常广泛，甚至延伸到了森林的边缘。 每个级别提供",
    "Your greatness of spirit grows and draws the attention of more important people. Each level invested allows you to hire": "你的伟大精神不断增强，并吸引了更重要的人的注意。 每个投资级别都允许您雇用",
    "Your growing experience with construction techniques start to reap benefits. The following advancements are made available at the start of each colony:": "您在施工技术方面不断积累的经验开始受益。 每个殖民地开始时都会提供以下进步：",
    "Your incredibly resilient mind unravels the mysteries of time better than anyone else by now. Cumulatively decreases the cost of": "到目前为止，你难以置信的弹性思维比任何人都更能解开时间的奥秘。 累计降低成本",
    "Your long-standing experience of civilization building grants you knowledge of how to maximize revenue. For each level, gain": "您长期的文明建设经验使您了解如何最大化收入。 对于每个级别，获得",
    "A new colony was built:": "建立了一个新的殖民地：",
    "Upper Spain": "西班牙北部",
    "You ventured and built your first the": "您冒险并建造了您的第一个",
    "ing this will allow you to make buildings. It seems like something worth looking into...": "这将允许你建造建筑物。 这似乎是值得研究的东西......",
    " and architecture come naturally to you. Reduces the cost of all": "建筑对你来说是自然而然的。 降低了大家的成本",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "ing": "",
    "Forresters": "福雷斯特斯人",
    "Outer Québec": "魁北克外省",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'er': '',
    'The': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Game Saved ": "游戏已保存 ",
    "Autosave": "自动保存",
    "Clicks: ": "点击次数: ",
    "Achievement Points: ": "成就点数: ",
    "Stone Quarries: ": "采石场: ",
    "Water Mills: ": "水磨坊: ",
    "Trades: ": "交易: ",
    "Upgrades: ": "升级: ",
    "Diamond: ": "钻石: ",
    "Water: ": "水: ",
    "Monks: ": "僧侣: ",
    "Wheat: ": "小麦: ",
    "Stone: ": "石头: ",
    "Wood: ": "木头: ",
    "Miners: ": "矿工: ",
    "Ironsmiths: ": "铁匠: ",
    "Grain Mills: ": "谷物磨坊: ",
    "Diamond Progress": "钻石产量",
    "Water Progress": "水产量",
    "Stone Progress": "石头产量",
    "Iron Progress": "铁产量",
    "Silver Progress": "银产量",
    "Wood Progress": "木头产量",
    "Wheat Progress": "小麦产量",
    "Always ": "总是 ",
    "TIP: ": "提示: ",
    "Bucket": "水桶",
    "Barrels": "木桶",
    "Wood Cart": "木车",
    "Shed": "棚子",
    "Water Dam": "水坝",
    "Mine Cart": "矿车",
    "Silver: ": "银: ",
    "Iron: ": "铁: ",
    "Casing (Iron)": "外壳（铁）",
    "Casing (Stone)": "外壳（石头）",
    "Casing (Water)": "外壳（水）",
    "Casing (Water)": "外壳（水）",
    "Casing (Wood)": "外壳（木）",
    "Water Tap": "水龙头",
    "Wood Tap": "木头水龙头",
    "Smart Tap": "智能水龙头",
    "Soft Tap": "软水龙头",
    "Iron Tap": "铁水龙头",
    "Stone Tap": "石头水龙头",
    "Silver Tap": "银水龙头",
    "Iron Sickle": "铁镰刀",
    "Forestry": "林业",
    "Deep Digging": "深挖",
    "Stonework": "石雕",
    "Masonry": "石加工",
    "Harvester": "收获者",
    "Harvest": "收获",
    "Hasty": "草率",
    "Iron Basket": "铁篮子",
    "Metalwork": "金属工",
    "Major Research: ": "主要研究方向：",
    "Wheat Tap": "小麦水龙头",
    "Scarcity": "缺乏",
    "Farmhouses": "农舍",
    "Motivation": "动机",
    "Slope Mining": "斜坡开采",
    "Better Quarries": "更好的采石场",
    "Iron Stock": "铁库存",
    "Stone Stock": "石头库存",
    "Water Stock": "水库存",
    "Wood Stock": "木头库存",
    "Wheat Stock": "小麦库存",
    "Silver Pickaxe": "银镐",
    "Tax Ceiling: ": "税收上限: ",
    "Tax Total: ": "税收总计: ",
    "Gold: ": "黄金: ",
    "Farm Work": "农场工作",
    "Fine Lumber": "优质木材",
    "Heavy Mining": "重型采矿",
    "Tree Care": "树木养护",
    "Regiment": "军团",
    "Silverwork": "银加工",
    "Diamond Pick.": "钻石镐。",
    "Diamond Pickaxe": "钻石镐",
    "Diamond Storage": "钻石存储",
    "Mining": "采矿",
    "Better Taxes": "更好的税收",
    "Diamond Stor.": "钻石存储",
    "Builder": "建设者",
    "Colonist": "殖民者",
    "Double Clicking": "双击",
    "Druidry": "德鲁伊",
    "Fire Dancer": "火舞者",
    "Engineer": "工程师",
    "Foreman": "工头",
    "Expertly curating and milling stones allows you to keep more of them. Grants each": "专业地整理和铣削宝石可以让您保留更多宝石。 补助金每",
    "Experts in the extraction of": "专家提取",
    "Expert": "专家",
    "Economist": "经济学家",
    "Fetching": "获取",
    "Haggler": "讨价还价者",
    "Head Start": "领先优势",
    "Heroism": "英雄主义",
    "Hoarding": "囤积",
    "Iron Minimalism": "铁极简主义",
    "Loop Clicking": "循环点击",
    "Lumberer": "伐木工",
    "Leaders Hired:": "聘请领导者：",
    "Leaders": "领导者",
    "Leader": "领导者",
    "Investment": "投资",
    "Mason": "石匠",
    "Maverick": "特立独行",
    "Mechanical Clicker": "机械点击器",
    "Merchant": "商人",
    "Milling": "铣削",
    "Research": "研究",
    "Opportunist": "机会主义者",
    "Resolve": "解决",
    "Advanced": "高级",
    "Wood Minimalism": "木质极简主义",
    "Water Dancer": "水舞者",
    "Weapon Master": "武器大师",
    "Wisdom": "智慧",
    "Stone Minimalism": "石材极简主义",
    "Taxman": "税务员",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec": "/秒",
    "/sec)": "/秒)",
    "% less": "% 变少",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^: ([\d\.]+)$/,
    /^: \-([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^ \(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+):([\d\.]+)\)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\+([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) has entered the$/, '$1 已进入'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^\+(.+) Maximum Wood$/, '\+$1 木头上限'],
    [/^\+(.+) Maximum Stone$/, '\+$1 石头上限'],
    [/^\+(.+) Maximum Iron$/, '\+$1 铁上限'],
    [/^\+(.+) Maximum Diamond Progress$/, '\+$1 最大钻石头产量'],
    [/^\+(.+)  Maximum Diamond Progress$/, '\+$1 最大钻石头产量'],
    [/^\+(.+) Maximum Stone Progress$/, '\+$1 最大石头产量'],
    [/^\+(.+) Maximum Water Progress$/, '\+$1 最大水产量'],
    [/^\+(.+)  Maximum Water Progress$/, '\+$1 最大水产量'],
    [/^\+(.+) Maximum Iron Progress$/, '\+$1 最大铁产量'],
    [/^\+(.+) Maximum Wood Progress$/, '\+$1 最大木头产量'],
    [/^\+(.+) Maximum Wheat Progress$/, '\+$1 最大小麦产量'],
    [/^\+(.+) Maximum Silver Progress$/, '\+$1 最大小银产量'],
    [/^\-(.+) Maximum Stone Progress$/, '\-$1 最大石头产量'],
    [/^\-(.+) Maximum Water Progress$/, '\-$1 最大水产量'],
    [/^\-(.+)  Maximum Water Progress$/, '\-$1 最大水产量'],
    [/^\-(.+) Maximum Iron Progress$/, '\-$1 最大铁产量'],
    [/^\-(.+) Maximum Wood Progress$/, '\-$1 最大木头产量'],
    [/^\-(.+) Maximum Wheat Progress$/, '\-$1 最大小麦产量'],
    [/^\-(.+) Maximum Silver Progress$/, '\-$1 最大小银产量'],
    [/^\+(.+) Maximum Capacity on All Resources$/, '\+$1 所有资源最大容量'],
    [/^\+([\d\.]+) per second$/, '\+$1 每秒'],
    [/^\+([\d\.]+) Wood Progress$/, '\+$1 木头产量'],
    [/^\+([\d\.]+) Water Storage Capacity$/, '\+$1 水存储容量'],
    [/^\+([\d\.]+) Wood Storage Capacity$/, '\+$1 木头存储容量'],
    [/^\+([\d\.]+) Stone Storage Capacity$/, '\+$1 石头存储容量'],
    [/^\+([\d\.]+) Water Progress per second$/, '\+$1 水产量每秒'],
    [/^\+([\d\.]+) Diamond Progress per second$/, '\+$1 钻石产量每秒'],
    [/^\+([\d\.]+) Wood Progress per second$/, '\+$1 木头产量每秒'],
    [/^\+([\d\.]+) Wood Progress and Stone Progress per second$/, '\+$1 木头产量和石头产量每秒'],
    [/^\+([\d\.]+) Stone Progress per second$/, '\+$1 石头产量每秒'],
    [/^\+([\d\.]+) Wheat Progress per second$/, '\+$1 小麦产量每秒'],
    [/^\+([\d\.]+) Silver Progress per second$/, '\+$1 银产量每秒'],
    [/^\+([\d\.]+) Iron Progress per second$/, '\+$1 铁产量每秒'],
    [/^([\d\.]+) Iron Progress per second$/, '$1 铁产量每秒'],
    [/^([\d\.]+) Wood Progress per second$/, '$1 木头产量每秒'],
    [/^([\d\.]+) Stone Progress per second$/, '$1 石头产量每秒'],
    [/^([\d\.]+) Wheat Progress per second$/, '$1 小麦产量每秒'],
    [/^([\d\.]+) Silver Progress per second$/, '$1 银产量每秒'],
    [/^([\d\.]+) Diamond Progress per second$/, '$1 钻石产量每秒'],
    [/^([\d\.]+) Stone per second$/, '$1 石头每秒'],
    [/^([\d\.]+) Water Progress per second$/, '$1 水产量每秒'],
    [/^([\d\.]+) Iron Progress per second$/, '$1 铁产量每秒'],
    [/^([\d\.]+) Wheat per second$/, '$1 小麦每秒'],
    [/^([\d\.]+) Wood per second$/, '$1 木头每秒'],
    [/^([\d\.]+) Silver per second$/, '$1 银每秒'],
    [/^([\d\.]+) Water per second$/, '$1 水每秒'],
    [/^\+([\d\.]+) Wheat per second$/, '\+$1 小麦每秒'],
    [/^\+([\d\.]+) Wood per second$/, '\+$1 木头每秒'],
    [/^([\d\.]+) Iron per second$/, '\+$1 铁每秒'],
    [/^\+([\d\.]+) Iron per second$/, '\+$1 铁每秒'],
    [/^\+([\d\.]+) Stone per second$/, '\+$1 石头每秒'],
    [/^\+([\d\.]+) Water per second$/, '\+$1 水每秒'],
    [/^\+([\d\.]+) Gold$/, '\+$1 黄金'],
    [/^\+([\d\.]+) Free Lumberjack$/, '\+$1 免费伐木工'],
    [/^\+([\d\.]+) Prestige Points$/, '\+$1 声望点数'],
    [/^([\d\.]+) Water per second.$/, '$1 水每秒。'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) Wood$/, '$1 木头'],
    [/^([\d\.]+) per second$/, '$1 每秒'],
    [/^([\d\.]+) per second.$/, '$1 每秒。'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Colony$/, '$1 殖民地'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Grain Mills$/, '$1 谷物磨坊'],
    [/^([\d\.,]+) Water Mills$/, '$1 水磨坊'],
    [/^([\d\.,]+) Ironsmiths$/, '$1 铁匠'],
    [/^([\d\.,]+) Stone Quarries$/, '$1 采石场'],
    [/^([\d\.,]+) Additional Buildings$/, '$1 额外的建筑'],
    [/^([\d\.,]+) Workers giving ([\d\.,]+) Gold$/, '$1 工人给予 $2 黄金'],
    [/^([\d\.,]+) Workers costing ([\d\.,]+) Gold$/, '$1 工人花费 $2 黄金'],
    [/^([\d\.,]+) Buildings giving ([\d\.,]+) Gold$/, '$1 建筑给予 $2 黄金'],
    [/^([\d\.,]+) Buildings costing ([\d\.,]+) Gold$/, '$1 建筑花费 $2 黄金'],
    [/^([\d\.,]+) Advancement Points$/, '$1 进阶点数'],
    [/^([\d\.,]+) clicks$/, '$1 点击'],
    [/^([\d\.,]+) Water$/, '$1 水'],
    [/^([\d\.,]+) Wheat$/, '$1 小麦'],
    [/^([\d\.,]+) Iron$/, '$1 铁'],
    [/^([\d\.,]+) Prestige Point$/, '$1 声望点数'],
    [/^([\d\.,]+) Prestige Points$/, '$1 声望点数'],
    [/^([\d\.,]+) Points$/, '$1 点数'],
    [/^([\d\.,]+) Diamond$/, '$1 钻石'],
    [/^([\d\.,]+) Silver$/, '$1 银'],
    [/^([\d\.,]+) Gold$/, '$1 黄金'],
    [/^([\d\.,]+) Stone$/, '$1 石头'],
    [/^([\d\.,]+) Monks$/, '$1 僧侣'],
    [/^([\d\.,]+) Trades$/, '$1 交易'],
    [/^([\d\.,]+) Upgrades$/, '$1 升级'],
    [/^([\d\.,]+) Clicks$/, '$1 点击'],
    [/^([\d\.,]+) Advancement Point$/, '$1 进阶点数'],
    [/^([\d\.,]+) ([\d\.,]+) Clicks$/, '$1 $2 点击'],
    [/^([\d\.,]+) Point$/, '$1 点数'],
    [/^([\d\.,]+) Point Available$/, '$1 点数可用'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);